---
- name: Install essential packages
  apt:
    name: [ 'net-tools', 'whois', 'htop', 'lvm2', 'gdisk', 'lsof', 'net-tools', 'gcc', "chrony", 'vim', 'wget', 'curl', 'screen']
    state: present


- name: Ensure chronyd is running
  service:
    name: chronyd
    state: started
    enabled: yes

