---
- name: Set timezone to Etc/UTC
  timezone:
    name: Etc/UTC

- name: Install rsyslog
  package:
    name: rsyslog
    state: present

- name: Restart rsyslog
  service:
    name: rsyslog
    state: restarted
    enabled: yes
